import React, { useState, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, ChevronLeft, ChevronRight, Send, Building2, Phone, Briefcase } from 'lucide-react'
import { CASE_CATEGORIES, CategoryConfig, FollowUpQuestion, getCategoryById } from '../config/caseCategories.config'
import { useIsMobile } from '../hooks/use-mobile'

interface RaiseACaseModalProps {
  isOpen: boolean
  onClose: () => void
  onSubmit: (caseData: CaseFormData) => Promise<void>
}

export interface CaseFormData {
  category: string
  title: string
  description: string
  followUpData: Record<string, string>
  vendorInfo?: {
    shopName: string
    contactNumber: string
    externalCompany: string
  }
}

type Step = 1 | 2 | 3

export default function RaiseACaseModal({ isOpen, onClose, onSubmit }: RaiseACaseModalProps) {
  const isMobile = useIsMobile()
  const [step, setStep] = useState<Step>(1)
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [followUpAnswers, setFollowUpAnswers] = useState<Record<string, string>>({})
  const [description, setDescription] = useState('')
  const [title, setTitle] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)

  // Vendor fields
  const [vendorShopName, setVendorShopName] = useState('')
  const [vendorContact, setVendorContact] = useState('')
  const [vendorCompany, setVendorCompany] = useState('')

  const categoryConfig = useMemo(() => {
    return selectedCategory ? getCategoryById(selectedCategory) : null
  }, [selectedCategory])

  const autoGeneratedTitle = useMemo(() => {
    if (!categoryConfig) return ''

    const parts: string[] = [categoryConfig.label]

    // Add first answer if available
    const firstQuestion = categoryConfig.followUpQuestions[0]
    if (firstQuestion && followUpAnswers[firstQuestion.id]) {
      parts.push(followUpAnswers[firstQuestion.id])
    }

    // Add issue type if available
    const issueTypeAnswer = followUpAnswers['issue_type'] || followUpAnswers['error_type'] || followUpAnswers['repair_type']
    if (issueTypeAnswer && issueTypeAnswer !== 'Other') {
      parts.push(`- ${issueTypeAnswer}`)
    }

    return parts.join(' ')
  }, [categoryConfig, followUpAnswers])

  const handleCategorySelect = (categoryId: string) => {
    setSelectedCategory(categoryId)
    setFollowUpAnswers({})
    setStep(2)
  }

  const handleFollowUpChange = (questionId: string, value: string) => {
    setFollowUpAnswers(prev => ({ ...prev, [questionId]: value }))
  }

  const canProceedToStep3 = useMemo(() => {
    if (!categoryConfig) return false

    const requiredQuestions = categoryConfig.followUpQuestions.filter(q => q.required)
    return requiredQuestions.every(q => followUpAnswers[q.id]?.trim())
  }, [categoryConfig, followUpAnswers])

  const handleSubmit = async () => {
    if (!selectedCategory || !categoryConfig) return

    setIsSubmitting(true)
    try {
      const caseData: CaseFormData = {
        category: selectedCategory,
        title: title || autoGeneratedTitle,
        description,
        followUpData: followUpAnswers,
      }

      if (categoryConfig.showVendorFields && (vendorShopName || vendorContact || vendorCompany)) {
        caseData.vendorInfo = {
          shopName: vendorShopName,
          contactNumber: vendorContact,
          externalCompany: vendorCompany,
        }
      }

      await onSubmit(caseData)
      handleReset()
      onClose()
    } catch (error) {
      console.error('Failed to create case:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleReset = () => {
    setStep(1)
    setSelectedCategory(null)
    setFollowUpAnswers({})
    setDescription('')
    setTitle('')
    setVendorShopName('')
    setVendorContact('')
    setVendorCompany('')
  }

  const handleClose = () => {
    handleReset()
    onClose()
  }

  if (!isOpen) return null

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="absolute inset-0 bg-black/50 backdrop-blur-sm"
          onClick={handleClose}
        />

        {/* Modal */}
        <motion.div
          initial={isMobile ? { y: '100%' } : { opacity: 0, scale: 0.95, y: 20 }}
          animate={isMobile ? { y: 0 } : { opacity: 1, scale: 1, y: 0 }}
          exit={isMobile ? { y: '100%' } : { opacity: 0, scale: 0.95, y: 20 }}
          transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          className={`relative w-full overflow-hidden ${
            isMobile 
            ? 'h-full bg-slate-50 flex flex-col pt-safe' 
            : 'max-w-2xl bg-white rounded-3xl shadow-2xl'
          }`}
        >
          {/* Header */}
          <div className={`${isMobile ? 'px-6 pt-12 pb-8' : 'px-6 py-5'} bg-gradient-to-r from-rose-500 to-amber-500 text-white flex-none`}>
            <div className="flex items-center justify-between">
              <div>
                <h2 className={isMobile ? "text-3xl font-black italic tracking-tighter uppercase" : "text-xl font-bold"}>Raise A Case</h2>
                <p className="text-white/80 text-sm mt-0.5 font-bold uppercase tracking-widest text-[10px]">
                  {step === 1 && 'What is this case related to?'}
                  {step === 2 && `${categoryConfig?.label} - Tell us more`}
                  {step === 3 && 'Review and submit'}
                </p>
              </div>
              <button
                onClick={handleClose}
                className={`p-2 hover:bg-white/20 rounded-full transition-colors ${isMobile ? 'bg-black/10' : ''}`}
              >
                <X size={20} />
              </button>
            </div>

            {/* Step Indicator */}
            <div className="flex items-center gap-2 mt-8">
              {[1, 2, 3].map((s) => (
                <div
                  key={s}
                  className={`h-1 flex-1 rounded-full transition-colors ${s <= step ? 'bg-white' : 'bg-white/30'
                    }`}
                />
              ))}
            </div>
          </div>

          {/* Content */}
          <div className={`p-6 overflow-y-auto flex-1 no-scrollbar ${isMobile ? 'pb-32' : 'max-h-[60vh]'}`}>
            <AnimatePresence mode="wait">
              {/* Step 1: Category Selection */}
              {step === 1 && (
                <motion.div
                  key="step1"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  className={`grid ${isMobile ? 'grid-cols-2' : 'grid-cols-3'} gap-4`}
                >
                  {CASE_CATEGORIES.filter(c => !['staff', 'vendor'].includes(c.id)).map((category) => (
                    <CategoryCard
                      key={category.id}
                      category={category}
                      isMobile={isMobile}
                      onClick={() => handleCategorySelect(category.id)}
                    />
                  ))}
                </motion.div>
              )}

              {/* Step 2: Follow-up Questions */}
              {step === 2 && categoryConfig && (
                <motion.div
                  key="step2"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-5"
                >
                  {/* Category Badge */}
                  <div
                    className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium"
                    style={{ backgroundColor: categoryConfig.bgColor, color: categoryConfig.color }}
                  >
                    <categoryConfig.icon size={16} />
                    {categoryConfig.label}
                  </div>

                  {/* Dynamic Questions */}
                  {categoryConfig.followUpQuestions.map((question) => (
                    <QuestionField
                      key={question.id}
                      question={question}
                      value={followUpAnswers[question.id] || ''}
                      onChange={(value) => handleFollowUpChange(question.id, value)}
                    />
                  ))}

                  {/* Vendor Fields */}
                  {categoryConfig.showVendorFields && (
                    <div className="mt-6 pt-6 border-t border-gray-100">
                      <div className="flex items-center gap-2 mb-4 text-gray-700">
                        <Briefcase size={18} />
                        <span className="font-semibold">External Vendor Information</span>
                        <span className="text-xs text-gray-400">(Optional)</span>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-600 mb-1.5">
                            <Building2 size={14} className="inline mr-1" />
                            Repair Shop / Vendor Name
                          </label>
                          <input
                            type="text"
                            value={vendorShopName}
                            onChange={(e) => setVendorShopName(e.target.value)}
                            placeholder="e.g., TechFix Solutions"
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-600 mb-1.5">
                            <Phone size={14} className="inline mr-1" />
                            Contact Number
                          </label>
                          <input
                            type="tel"
                            value={vendorContact}
                            onChange={(e) => setVendorContact(e.target.value)}
                            placeholder="e.g., +91 9876543210"
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
                          />
                        </div>

                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-600 mb-1.5">
                            External Company / Firm
                          </label>
                          <input
                            type="text"
                            value={vendorCompany}
                            onChange={(e) => setVendorCompany(e.target.value)}
                            placeholder="e.g., ABC Services Pvt Ltd"
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
                          />
                        </div>
                      </div>
                    </div>
                  )}
                </motion.div>
              )}

              {/* Step 3: Description & Submit */}
              {step === 3 && categoryConfig && (
                <motion.div
                  key="step3"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-5"
                >
                  {/* Summary Card */}
                  <div className="p-4 bg-gray-50 rounded-2xl border border-gray-100">
                    <div className="flex items-center gap-2 mb-3">
                      <div
                        className="p-2 rounded-lg"
                        style={{ backgroundColor: categoryConfig.bgColor }}
                      >
                        <categoryConfig.icon size={18} style={{ color: categoryConfig.color }} />
                      </div>
                      <span className="font-semibold text-gray-800">{categoryConfig.label}</span>
                    </div>

                    <div className="space-y-1.5 text-sm">
                      {categoryConfig.followUpQuestions.map((q) => (
                        followUpAnswers[q.id] && (
                          <div key={q.id} className="flex">
                            <span className="text-gray-500 w-32 flex-shrink-0">{q.label}:</span>
                            <span className="text-gray-800 font-medium">{followUpAnswers[q.id]}</span>
                          </div>
                        )
                      ))}

                      {/* Vendor Summary */}
                      {categoryConfig.showVendorFields && vendorShopName && (
                        <>
                          <div className="border-t border-gray-200 my-2 pt-2">
                            <span className="text-xs font-semibold text-gray-400 uppercase">Vendor Info</span>
                          </div>
                          {vendorShopName && (
                            <div className="flex">
                              <span className="text-gray-500 w-32 flex-shrink-0">Shop:</span>
                              <span className="text-gray-800 font-medium">{vendorShopName}</span>
                            </div>
                          )}
                          {vendorContact && (
                            <div className="flex">
                              <span className="text-gray-500 w-32 flex-shrink-0">Contact:</span>
                              <span className="text-gray-800 font-medium">{vendorContact}</span>
                            </div>
                          )}
                          {vendorCompany && (
                            <div className="flex">
                              <span className="text-gray-500 w-32 flex-shrink-0">Company:</span>
                              <span className="text-gray-800 font-medium">{vendorCompany}</span>
                            </div>
                          )}
                        </>
                      )}
                    </div>
                  </div>

                  {/* Title Field */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1.5">
                      Case Title
                    </label>
                    <input
                      type="text"
                      value={title || autoGeneratedTitle}
                      onChange={(e) => setTitle(e.target.value)}
                      placeholder="Auto-generated title (you can edit)"
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all font-medium"
                    />
                    <p className="mt-1 text-xs text-gray-400">
                      Title is auto-generated based on your answers. Feel free to modify.
                    </p>
                  </div>

                  {/* Description Field */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1.5">
                      Additional Details <span className="text-gray-400 font-normal">(Optional)</span>
                    </label>
                    <textarea
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      placeholder="Describe the issue in your own words..."
                      rows={4}
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all resize-none"
                    />
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Footer */}
          <div className="px-6 py-4 border-t border-gray-100 bg-gray-50/50 flex items-center justify-between">
            <div>
              {step > 1 && (
                <button
                  onClick={() => setStep((s) => (s - 1) as Step)}
                  className="flex items-center gap-1.5 px-4 py-2 text-gray-600 hover:text-gray-800 font-medium transition-colors"
                >
                  <ChevronLeft size={18} />
                  Back
                </button>
              )}
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={handleClose}
                className="px-4 py-2 text-gray-600 hover:text-gray-800 font-medium transition-colors"
              >
                Cancel
              </button>

              {step === 2 && (
                <button
                  onClick={() => setStep(3)}
                  disabled={!canProceedToStep3}
                  className="flex items-center gap-1.5 px-5 py-2.5 bg-gradient-to-r from-rose-500 to-amber-500 text-white font-semibold rounded-xl hover:shadow-lg hover:shadow-rose-200 disabled:opacity-50 disabled:hover:shadow-none transition-all"
                >
                  Next
                  <ChevronRight size={18} />
                </button>
              )}

              {step === 3 && (
                <button
                  onClick={handleSubmit}
                  disabled={isSubmitting}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-rose-500 to-amber-500 text-white font-semibold rounded-xl hover:shadow-lg hover:shadow-rose-200 disabled:opacity-50 transition-all"
                >
                  {isSubmitting ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Submitting...
                    </>
                  ) : (
                    <>
                      <Send size={18} />
                      Submit Case
                    </>
                  )}
                </button>
              )}
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}

// Category Card Component
function CategoryCard({ category, onClick, isMobile }: { category: CategoryConfig; onClick: () => void, isMobile?: boolean }) {
  return (
    <motion.button
      whileHover={isMobile ? {} : { scale: 1.02 }}
      whileTap={{ scale: 0.96 }}
      onClick={onClick}
      className={`${isMobile ? 'p-6 rounded-[35px] shadow-sm' : 'p-4 rounded-2xl border-2'} border-gray-100 hover:border-gray-200 bg-white hover:bg-gray-50 transition-all group text-left flex flex-col items-center text-center`}
    >
      <div
        className={`${isMobile ? 'w-14 h-14 rounded-2xl mb-4 shadow-lg' : 'w-12 h-12 rounded-xl mb-3'} flex items-center justify-center transition-transform group-hover:scale-110`}
        style={{ backgroundColor: category.bgColor }}
      >
        <category.icon size={isMobile ? 28 : 24} style={{ color: category.color }} />
      </div>
      <h3 className="font-black text-slate-800 text-[10px] uppercase tracking-widest leading-tight">{category.label}</h3>
    </motion.button>
  )
}

// Question Field Component
function QuestionField({
  question,
  value,
  onChange
}: {
  question: FollowUpQuestion
  value: string
  onChange: (value: string) => void
}) {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1.5">
        {question.label}
        {question.required && <span className="text-rose-500 ml-1">*</span>}
      </label>

      {question.type === 'select' && question.options ? (
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all appearance-none cursor-pointer"
        >
          <option value="">Select an option...</option>
          {question.options.map((opt) => (
            <option key={opt} value={opt}>{opt}</option>
          ))}
        </select>
      ) : question.type === 'textarea' ? (
        <textarea
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={question.placeholder}
          rows={3}
          className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all resize-none"
        />
      ) : question.type === 'date' ? (
        <input
          type="date"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
        />
      ) : question.type === 'time' ? (
        <input
          type="time"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
        />
      ) : (
        <input
          type="text"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={question.placeholder}
          className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-rose-500/30 focus:border-rose-500 outline-none transition-all"
        />
      )}
    </div>
  )
}
